### PR TITLE
rename nuxt imports, add back nuxt(3) testing

### PR DESCRIPTION
**Pull request by JulienMartel**
nuxt3 is renamed as nuxt, and nuxt2 is named appropriately, as they are in the CLI repo

### CODE REVIEW

**Comment by JulienMartel** [comment]
@alexastrum could we try running this workflow again?

**Review by alexastrum — APPROVED** [review]

**Comment by alexastrum** [comment]
Not sure why custom tests fail here, but succeed elsewhere

**Review by alexastrum — APPROVED** [review]

**Comment by alexastrum** [comment]
@JulienMartel 

> npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

**Review by alexastrum — CHANGES_REQUESTED** [review]
https://github.com/FirebaseExtended/firebase-framework-tools/actions/runs/5941003212/job/16112355646?pr=100

**Comment by JulienMartel** [comment]
@alexastrum It was a type-error coming from next.js

I fixed it by changing the way `next` is being imported, it seems to build locally with no errors.

Can we run this workflow again? Thanks:)

**Review by alexastrum — APPROVED** [review]

**Comment by JulienMartel** [comment]
Hey @alexastrum! I'm having trouble getting the "custom" test to fail locally, as it has been in the recent workflow runs. 

I added a `--debug` flag to the "custom" emulator command so that we can get a better idea of why it's failing in the workflow.

Could you approve a re-run again? Thanks in advance 🙏

**Comment by alexastrum** [comment]
Not sure if this is still relevant

**Pull request closed without merging**
