### PR TITLE
fix: sveltekit server endpoint buffer response

### PR DESCRIPTION
**Pull request by m3tasploit**
Fix for corrupt images when responding with image/jpeg or any binary data from sveltekit Api endpoint

### CODE REVIEW

**Comment by jamesdaniels** [comment]
@m3tasploit LGTM. Q, does the text content-type repsonse work ok if you always respond with a buffer? Best to avoid conditionals when possible

**Comment by m3tasploit** [comment]
Oh, sorry i forgot that case, I'll try different content types and update code of necessary

**Comment by m3tasploit** [comment]
> @m3tasploit LGTM. Q, does the text content-type repsonse work ok if you always respond with a buffer? Best to avoid conditionals when possible

I've added check for commonly used text content-types. I'm not sure if this is the correct way to go.

**Comment by leoortizz** [comment]
Hey @m3tasploit, thanks for creating this PR. I did a few tests and found that if we always respond with a buffer it also works, therefore avoiding conditionals. Implemented in #205.

**Comment by leoortizz** [comment]
Merged in https://github.com/FirebaseExtended/firebase-framework-tools/pull/205

**Pull request closed without merging**
